# OPENAI Models
GPT_4_1_MINI = "gpt-4.1-mini"
GPT_4_1 = "gpt-4.1"

# PROVIDERS
OPENAI = "openai"

# TRACING
## SPAN Kinds
INIT = "INIT"
DATABASE = "DATABASE"
CACHE = "CACHE"
VECTOR_INDEX = "VECTOR_INDEX"
