# OPENAI Models
GPT_4_1_MINI = "gpt-4.1-mini"
GPT_4_1 = "gpt-4.1"
TEXT_EMBEDDING_3_SMALL = "text-embedding-3-small"

# PROVIDERS
OPENAI = "openai"

# TRACING
## SPAN Kinds
INIT = "INIT"
DATABASE = "DATABASE"
CACHE = "CACHE"
VECTOR_INDEX = "VECTOR_INDEX"
