# SERVER
SERVER_STARTUP = "SERVER_STARTUP"
SERVER_SHUTDOWN = "SERVER_SHUTDOWN"

# Span Kind
SERVER = "SERVER"

# Session backend selection
SESSION_BACKEND_MONGO = "mongo"
DEFAULT_SESSION_BACKEND = SESSION_BACKEND_MONGO
